# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SampleApp' do
    use_frameworks!
    
    pod 'EddystoneScanner'
    pod 'Socket.IO-Client-Swift', '15.2.0'
    pod 'Imaginary'
end

post_install do |installer|
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          end
        end
      end
